### ISSUE TITLE
Comparison to other multi agent collaboration frameworks

### ISSUE THREAD

**Issue by agokrani** [agiresearch/AIOS#8]
Hi,
Very interesting work, I do like the idea a lot and see a huge potential in this becoming defacto way of dealing with LLM agents. 

I would like to know how would you compare yourself with other opensource frameworks for multi agent collaboration like LangGraph, Autogen, CrewAI etc. Do you see a path forward where you would have them integrated into your kernel or even the app layer? And specifically how do you see LangGraph's finite state machines approach being integrated into this OS?

**Comment by dongyuanjushi** [comment]
Thanks a lot for your recognition. In our understanding, current multi-agent collaboration frameworks build agent applications rather than manage. The built multi-agent instances are still application-level, meaning that they are also applications like the single agent instances from the perspective of AIOS. In current version, we use some single agent instances to illustrate the main procedure, and we will keep updated to incorporate more agent applications like the multi-agent ones and support their mechanisms.

**Comment by agokrani** [comment]
@dongyuanjushi thank you so much for the quick response. I think multi agent collaboration is going to be super important. If you have ideas already that you would like to implement. Can we discuss them? I am interested in contributing to some of these ideas.

**Comment by dongyuanjushi** [comment]
Thank you for your interest and support. We are developing some implementation plans. It will be great to discuss with you when we evaluate and make sure some of the plans are plausible. And if you have your own implementation ideas and want to share, feel free to contact us. It will be greatly appreciated!

**Comment by hemangjoshi37a** [comment]
Is there any video available about this repo on how it looks and works? Thanks
